image: fpco/stack-build:lts-10.10

stages:
  - build
  - deploy

build:
  stage: build
  variables:
    STACK_ROOT: "${CI_PROJECT_DIR}/.stack"
  cache:
    paths:
      - .stack-work
      - .stack
  artifacts:
    paths:
      - binaries
  script:
    - mkdir -p .stack binaries
    - stack install --system-ghc --local-bin-path binaries

pages:
  stage: deploy
  cache:
    paths:
      - _cache
      - _site
  script:
    - ./binaries/timbaumann build
    - cp -R _site public
  artifacts:
    paths:
      - public