# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

branches:
  only:
    - source

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack --no-terminal build -j 1 Cabal
- stack --no-terminal --install-ghc install

before_script:
  - git config --global user.email "travis@timbaumann.info"
  - git config --global user.name "Travis"
  - mkdir -m 700 -p $HOME/.ssh
  - echo "$SSH_DEPLOY_KEY" | base64 -d > $HOME/.ssh/id_rsa
  - chmod 600 $HOME/.ssh/id_rsa

script:
- ./deploy.sh git@github.com:timjb/timjb.github.io.git